input:
  broker:
    inputs:
      - label: ainput
        kafka:
          addresses: ['localhost:1234']
          topics: [a, b, c]
        processors:
          - label: amapper
            bloblang: 'root = this'
          - label: bmapper
            bloblang: 'root = this'
      - label: binput
        nats_jetstream:
          urls: ['nats://localhost:1234']
          subject: a
      - label: aqw
        aws_kinesis: null
  processors:
    - label: cmapper
      bloblang: 'root = this'
    - label: dmapper
      bloblang: 'root = this'
pipeline:
  processors:
    - awk:
        program: 'BEGIN { print "foo"; }'
    - archive:
        format: tar
    - compress:
        algorithm: gzip
output:
  broker:
    outputs:
      - amqp_0_9:
          exchange: benthos-exchange
          key: benthos-key
        processors:
          - label: gmapper
            bloblang: 'root = this'
          - label: hmapper
            bloblang: 'root = this'
      - nats_jetstream:
          urls: ['nats://localhost:1234']
          subject: a
  processors:
    - label: emapper
      bloblang: 'root = this'
    - label: fmapper
      bloblang: 'root = this'
processor_resources:
  - label: fooproc
    branch:
      processors:
        - bloblang: 'root = this'
        - bloblang: 'root = this'
        - bloblang: 'root = this'
  - label: barproc
    bloblang: 'root = this'
cache_resources:
  - label: foocache
    memory: {}
