http:
  enabled: false
input:
  broker:
    inputs:
      - label: fooinput
        generate:
          mapping: 'root = "hello world"'
          interval: 1s
          count: 0
      - label: ""
        aws_kinesis:
          streams:
            - test
          dynamodb:
            table: ""
            create: false
            billing_mode: PAY_PER_REQUEST
            read_capacity_units: 0
            write_capacity_units: 0
          checkpoint_limit: 1024
          auto_replay_nacks: true
          commit_period: 5s
          steal_grace_period: 2s
          rebalance_period: 30s
          lease_period: 30s
          start_from_oldest: true
          batching:
            count: 0
            byte_size: 0
            period: ""
            check: ""
buffer:
  memory: {}
pipeline:
  processors:
    - label: fooproc
      mapping: 'root = content().uppercase()'
output:
  label: foooutput
  drop: {}
