pipeline:
  processors:
    - label: ""
      http:
        url: df
        verb: POST
        metadata:
          include_prefixes: []
          include_patterns: []
        dump_request_log_level: ""
        oauth:
          enabled: false
          consumer_key: ""
          consumer_secret: ""
          access_token: ""
          access_token_secret: ""
        oauth2:
          enabled: false
          client_key: ""
          client_secret: ""
          token_url: ""
          scopes: []
        basic_auth:
          enabled: false
          username: ""
          password: ""
        jwt:
          enabled: false
          private_key_file: ""
          signing_method: ""
        tls:
          enabled: false
          skip_cert_verify: false
          enable_renegotiation: false
          root_cas: ""
          root_cas_file: ""
          client_certs: []
        extract_headers:
          include_prefixes: []
          include_patterns: []
        timeout: 5s
        retry_period: 1s
        max_retry_backoff: 300s
        retries: 3
        follow_redirects: true
        backoff_on: []
        drop_on: []
        successful_on: []
        disable_http2: false
        batch_as_multipart: false
        parallel: false
    - label: sdasdasdasdasdasdasdasdasdasdasdasd
      mapping: sfsdf
